# Generated by Django 2.0.1 on 2018-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0016_auto_20180131_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
