# Generated by Django 2.0.1 on 2018-02-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0022_auto_20180201_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(null=True, upload_to='.'),
        ),
    ]
